# Generated by Django 4.1.3 on 2022-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_delete_category_article_category_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('HISTORY', 'History'), ('NATURE', 'Nature'), ('SCIENCE', 'Science'), ('PHILOSOPHY', 'Philosophy'), ('POLITICAL', 'Political')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
