# Generated by Django 4.1.3 on 2022-11-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('HISTORY', 'History'), ('NATURE', 'Nature'), ('SCIENCE', 'Science'), ('PHILOSOPHY', 'Philosophy'), ('POLITICAL', 'Political')], max_length=15, null=True),
        ),
    ]
